### ISSUE TITLE
第五章练习1的叙述有误

### ISSUE THREAD

**Issue by ctgnauh** [DeathKing/yast-cn#11]
原文是：

> The integers that can be converted to graphical characters are 33 – 126. 

翻译：

>  整数可以被转化为33-126号之间的ASCII码。

但是答案中函数的功能是：将33-126之间的整数转换成ASCII。

**Comment by DeathKing** [comment]
不好意思，我竟然现在才看到这个 issue 。

这句话应该是想要表达：“只有在33~126之间的ASCII码才能转换为可见的字符”。

多谢指出，已修改！

**Comment by ctgnauh** [comment]
后来我直接啃的原版……

Dinesta Xenophon Fisper <notifications@github.com<mailto:notifications@github.com>>于2016 年 6 月 20 日周一 12:49写道：

不好意思，我竟然现在才看到这个 issue 。

这句话应该是想要表达：“只有在33~126之间的ASCII码才能转换为可见的字符”。

多谢指出，已修改！
