### ISSUE TITLE
15章向量和结构体vector-add函数有误

### ISSUE THREAD

**Issue by vincent1853** [DeathKing/yast-cn#34]
15.向量和结构体
例：一个对向量中元素求和的函数。
vector-add函数应该为：
`(define (vector-add v1 v2)
       (let ((lenv1 (vector-length v1))
         (lenv2 (vector-length v2)))
         (if (= lenv1 lenv2)
         (let ((v (make-vector lenv1)))
           (let loop ((i 0))
             (if (= i lenv1)
             v
             (begin
               (vector-set! v i (+ (vector-ref v1 i) (vector-ref v2 i)))
               (loop (+ 1 i))))))
        (error "different dimensions."))))`

**Comment by DeathKing** [comment]
@vincent1853  看了下，原书确实是用的 1+ 这个过程。
在 SICP 视频中，教授们也经常使用这种简便记法。

其实是否修改并无紧要，不过考虑到这是一份新手入门教程，如果拷贝的代码不能正常运行，会给严重打击大家的学习积极性，所以我还是把这个给 fix 了。
