### ISSUE TITLE
第三章三角函数这一节有错误

### ISSUE THREAD

**Issue by dccxi** [DeathKing/yast-cn#35]
atan 的第二个参数并不是用来指示弧度，而是：

1. 一个参数时求该数的 atan 值
2. 两个参数时求两个参数相除之后的 atan 值

`(atan z)` 计算 z 的 arctangent，`(atan y x)` 等于 `(angle (make-rectangular x y))`，两者结果均为弧度

参考：https://www.gnu.org/software/mit-scheme/documentation/mit-scheme-ref/Numerical-operations.html#Numerical-operations

**Comment by DeathKing** [comment]
@dccxi 看了下原文，应该是我理解有误：

> if the value of atan is expected to be 1/2 π, use two arguments.

原作者的意思是，如果 `atan` 的参数为 90°（也就是 1/2 弧度），那么就使用两个参数来计算，也就是你提到的两个参数相除。大概是因为 `(tan 90°) = +inf`。
